### ISSUE TITLE
About mixins

### ISSUE THREAD

**Issue by juanbrujo** [inuitless/inuit.css#13]
Why are you saying "no keyframe mixin, no media-query mixin"?

There's a great [@keyframe mixin](http://codepen.io/juanbrujo/pen/EadVJJ) written in LESS and [@media mixin](https://gist.github.com/juanbrujo/bb3a8897b12773496d72), of course.

**Comment by nicoespeon** [comment]
Hi @juanbrujo!

You're completely right. The reason for that is that it wasn't something feasible when it was coded:
- LESS `v1.7.0` makes possible the `@keyframe` mixin in Feb. 2014
- LESS `v1.3.0` makes possible the `@media` mixin by the end of 2012 

We could have updated this and use new versions of LESS since. But I fear the repo is a bit outdated for now, and I personally didn't find the time to maintain it for months. Actually, I think there is a lot to catch up with the inuit.css SASS project, but we need to find some time — or help :smile:
